"""HTML report generation."""

from pathlib import Path
from typing import Optional

from llmtest_perf.compare.verdicts import ComparisonVerdict
from llmtest_perf.engine.metrics import AggregatedMetrics, PercentileStats


class HTMLReporter:
    """Generates self-contained HTML reports."""

    def _format_percentiles_table(
        self, stats: Optional[PercentileStats], title: str
    ) -> str:
        """Generate HTML table for percentile stats."""
        if not stats:
            return f"<p><em>{title}: No data available</em></p>"

        return f"""
        <h3>{title}</h3>
        <table>
            <tr><th>Percentile</th><th>Value</th></tr>
            <tr><td>P50</td><td>{stats.p50:.2f} ms</td></tr>
            <tr><td>P90</td><td>{stats.p90:.2f} ms</td></tr>
            <tr><td>P95</td><td>{stats.p95:.2f} ms</td></tr>
            <tr><td>P99</td><td>{stats.p99:.2f} ms</td></tr>
            <tr><td>Mean</td><td>{stats.mean:.2f} ms</td></tr>
            <tr><td>Min</td><td>{stats.min:.2f} ms</td></tr>
            <tr><td>Max</td><td>{stats.max:.2f} ms</td></tr>
        </table>
        """

    def generate_single_target_report(
        self, metrics: AggregatedMetrics, output_path: str
    ) -> None:
        """Generate HTML report for single target."""
        html_content = f"""
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Performance Test Report: {metrics.target_name}</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 40px; background: #f5f5f5; }}
        .container {{ max-width: 1200px; margin: 0 auto; background: white; padding: 30px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }}
        h1 {{ color: #333; border-bottom: 3px solid #007bff; padding-bottom: 10px; }}
        h2 {{ color: #555; margin-top: 30px; }}
        h3 {{ color: #666; margin-top: 20px; }}
        table {{ width: 100%; border-collapse: collapse; margin: 20px 0; }}
        th, td {{ padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }}
        th {{ background-color: #007bff; color: white; }}
        tr:hover {{ background-color: #f5f5f5; }}
        .summary-card {{ display: inline-block; margin: 10px; padding: 20px; background: #f8f9fa; border-radius: 5px; min-width: 200px; }}
        .summary-card .label {{ font-size: 14px; color: #666; }}
        .summary-card .value {{ font-size: 28px; font-weight: bold; color: #007bff; }}
        .error {{ color: #dc3545; }}
        .success {{ color: #28a745; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>Performance Test Report</h1>
        <h2>Target: {metrics.target_name}</h2>

        <h2>Summary</h2>
        <div class="summary-card">
            <div class="label">Total Requests</div>
            <div class="value">{metrics.total_requests}</div>
        </div>
        <div class="summary-card">
            <div class="label">Success Rate</div>
            <div class="value class="success">{100 - metrics.error_rate_percent:.1f}%</div>
        </div>
        <div class="summary-card">
            <div class="label">Throughput</div>
            <div class="value">{metrics.requests_per_sec:.1f} req/s</div>
        </div>
        <div class="summary-card">
            <div class="label">Token Throughput</div>
            <div class="value">{metrics.output_tokens_per_sec:.1f} tok/s</div>
        </div>

        {self._format_percentiles_table(metrics.latency, "Latency Percentiles")}
        {self._format_percentiles_table(metrics.ttft, "Time to First Token (TTFT)")}

        <h2>Error Summary</h2>
        <p>Error Rate: <span class="error">{metrics.error_rate_percent:.2f}%</span></p>
        {self._format_error_table(metrics.error_breakdown)}

        <h2>Per-Prompt-Set Breakdown</h2>
        {self._format_prompt_set_tables(metrics)}

        <footer style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; color: #999; font-size: 12px;">
            Generated by llmtest-perf
        </footer>
    </div>
</body>
</html>
"""
        output_file = Path(output_path)
        output_file.parent.mkdir(parents=True, exist_ok=True)

        with open(output_file, "w", encoding="utf-8") as f:
            f.write(html_content)

    def _format_error_table(self, error_breakdown: dict[str, int]) -> str:
        """Format error breakdown table."""
        if not error_breakdown:
            return "<p><em>No errors</em></p>"

        rows = "".join(
            f"<tr><td>{error_type}</td><td>{count}</td></tr>"
            for error_type, count in sorted(
                error_breakdown.items(), key=lambda x: x[1], reverse=True
            )
        )

        return f"""
        <table>
            <tr><th>Error Type</th><th>Count</th></tr>
            {rows}
        </table>
        """

    def _format_prompt_set_tables(self, metrics: AggregatedMetrics) -> str:
        """Format per-prompt-set metrics."""
        if not metrics.prompt_set_metrics:
            return "<p><em>No prompt set data</em></p>"

        html = ""
        for name, ps_metrics in metrics.prompt_set_metrics.items():
            latency_val = f"{ps_metrics.latency.p95:.2f} ms" if ps_metrics.latency else "N/A"
            ttft_val = f"{ps_metrics.ttft.p95:.2f} ms" if ps_metrics.ttft else "N/A"

            html += f"""
            <h3>Prompt Set: {name}</h3>
            <table>
                <tr><td>Total Requests</td><td>{ps_metrics.total_requests}</td></tr>
                <tr><td>Success Rate</td><td>{100 - ps_metrics.error_rate_percent:.1f}%</td></tr>
                <tr><td>P95 Latency</td><td>{latency_val}</td></tr>
                <tr><td>P95 TTFT</td><td>{ttft_val}</td></tr>
            </table>
            """

        return html

    def generate_comparison_report(
        self,
        verdict: ComparisonVerdict,
        baseline_metrics: AggregatedMetrics,
        candidate_metrics: AggregatedMetrics,
        output_path: str,
    ) -> None:
        """Generate HTML comparison report."""
        verdict_color = "#28a745" if verdict.status.value == "PASS" else "#dc3545"

        comparison_rows = ""
        for metric in verdict.metrics:
            bl_val = f"{metric.baseline_value:.2f}" if metric.baseline_value is not None else "N/A"
            ca_val = f"{metric.candidate_value:.2f}" if metric.candidate_value is not None else "N/A"
            delta = f"{metric.delta_percent:+.1f}%" if metric.delta_percent is not None else "N/A"

            if metric.is_regression:
                status = '<span style="color: #dc3545;">REGRESSION</span>'
            elif metric.is_improvement:
                status = '<span style="color: #28a745;">IMPROVEMENT</span>'
            else:
                status = '<span style="color: #999;">OK</span>'

            comparison_rows += f"""
            <tr>
                <td>{metric.metric_name}</td>
                <td>{bl_val}</td>
                <td>{ca_val}</td>
                <td>{delta}</td>
                <td>{status}</td>
            </tr>
            """

        html_content = f"""
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Performance Comparison Report</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 40px; background: #f5f5f5; }}
        .container {{ max-width: 1200px; margin: 0 auto; background: white; padding: 30px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }}
        h1 {{ color: #333; border-bottom: 3px solid #007bff; padding-bottom: 10px; }}
        h2 {{ color: #555; margin-top: 30px; }}
        table {{ width: 100%; border-collapse: collapse; margin: 20px 0; }}
        th, td {{ padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }}
        th {{ background-color: #007bff; color: white; }}
        tr:hover {{ background-color: #f5f5f5; }}
        .verdict-box {{ padding: 30px; margin: 30px 0; background: {verdict_color}; color: white; border-radius: 8px; text-align: center; }}
        .verdict-box h2 {{ color: white; margin: 0 0 10px 0; border: none; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>Performance Comparison Report</h1>
        <p><strong>Baseline:</strong> {verdict.baseline_target}</p>
        <p><strong>Candidate:</strong> {verdict.candidate_target}</p>

        <div class="verdict-box">
            <h2>{verdict.status.value}</h2>
            <p>{verdict.summary}</p>
            <p><strong>{verdict.recommendation}</strong></p>
        </div>

        <h2>Metric Comparison</h2>
        <table>
            <tr>
                <th>Metric</th>
                <th>Baseline</th>
                <th>Candidate</th>
                <th>Delta</th>
                <th>Status</th>
            </tr>
            {comparison_rows}
        </table>

        <footer style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; color: #999; font-size: 12px;">
            Generated by llmtest-perf
        </footer>
    </div>
</body>
</html>
"""

        output_file = Path(output_path)
        output_file.parent.mkdir(parents=True, exist_ok=True)

        with open(output_file, "w", encoding="utf-8") as f:
            f.write(html_content)
